/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class DEVICEElement {
	@SerializedName("MSO_FLD_EXT_WARRANTY_END")
	private String mso_fld_ext_warranty_end;

 	public void setMso_fld_ext_warranty_end(String mso_fld_ext_warranty_end) {
		this.mso_fld_ext_warranty_end = mso_fld_ext_warranty_end;
	}

	public String getMso_fld_ext_warranty_end() {
		return mso_fld_ext_warranty_end;
	}

	@SerializedName("SOURCE")
	private String source;

 	public void setSource(String source) {
		this.source = source;
	}

	public String getSource() {
		return source;
	}

	@SerializedName("DESCR")
	private String descr;

 	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getDescr() {
		return descr;
	}

	@SerializedName("POID")
	private String poid;

 	public void setPoid(String poid) {
		this.poid = poid;
	}

	public String getPoid() {
		return poid;
	}

	@SerializedName("DEVICE_ID")
	private String device_id;

 	public void setDevice_id(String device_id) {
		this.device_id = device_id;
	}

	public String getDevice_id() {
		return device_id;
	}

	@SerializedName("elem")
	private String elem;

 	/*public void setElem(Integer elem) {
		this.elem = elem;
	}*/

	public Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@SerializedName("MSO_FLD_SERIAL_NO")
	private String mso_fld_serial_no;

 	public void setMso_fld_serial_no(String mso_fld_serial_no) {
		this.mso_fld_serial_no = mso_fld_serial_no;
	}

	public String getMso_fld_serial_no() {
		return mso_fld_serial_no;
	}

	@SerializedName("MODEL")
	private String model;

 	public void setModel(String model) {
		this.model = model;
	}

	public String getModel() {
		return model;
	}

	@SerializedName("MSO_FLD_WARRANTY_END")
	private String mso_fld_warranty_end;

 	public void setMso_fld_warranty_end(String mso_fld_warranty_end) {
		this.mso_fld_warranty_end = mso_fld_warranty_end;
	}

	public String getMso_fld_warranty_end() {
		return mso_fld_warranty_end;
	}

	@SerializedName("MANUFACTURER")
	private String manufacturer;

 	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getManufacturer() {
		return manufacturer;
	}

	@SerializedName("DEVICE_TYPE")
	private String device_type;

 	public void setDevice_type(String device_type) {
		this.device_type = device_type;
	}

	public String getDevice_type() {
		return device_type;
	}

	@SerializedName("MSO_FLD_WARRANTY_END_OFFSET")
	private Integer mso_fld_warranty_end_offset;

 	public void setMso_fld_warranty_end_offset(Integer mso_fld_warranty_end_offset) {
		this.mso_fld_warranty_end_offset = mso_fld_warranty_end_offset;
	}

	public Integer getMso_fld_warranty_end_offset() {
		return mso_fld_warranty_end_offset;
	}

	@SerializedName("STATE_ID")
	private Integer state_id;

 	public void setState_id(Integer state_id) {
		this.state_id = state_id;
	}

	public Integer getState_id() {
		return state_id;
	}

}