/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import org.codehaus.jackson.annotate.JsonProperty;

public class GROUP_INFO {
	
	@JsonProperty("ACCOUNT_NO")
	private String account_no;

 	public void setAccount_no(String account_no) {
		this.account_no = account_no;
	}

	public String getAccount_no() {
		return account_no;
	}

	@JsonProperty("NAMEINFO")
	private NAMEINFO nameinfo;

 	public void setNameinfo(NAMEINFO nameinfo) {
		this.nameinfo = nameinfo;
	}

	public NAMEINFO getNameinfo() {
		return nameinfo;
	}

	@JsonProperty("POID")
	private String poid;

 	public void setPoid(String poid) {
		this.poid = poid;
	}

	public String getPoid() {
		return poid;
	}

	@JsonProperty("MODEL")
	private Integer model;

 	public void setModel(Integer model) {
		this.model = model;
	}

	public Integer getModel() {
		return model;
	}

	@JsonProperty("MEMBERS")
	private MEMBERElement[] members;

 	public void setMembers(MEMBERElement[] members) {
		this.members = members;
	}

	public MEMBERElement[] getMembers() {
		return members;
	}

	@JsonProperty("CONN_TYPE")
	private Integer conn_type;

 	public void setConn_type(Integer conn_type) {
		this.conn_type = conn_type;
	}

	public Integer getConn_type() {
		return conn_type;
	}

	@JsonProperty("PARENT")
	private String parent;

 	public void setParent(String parent) {
		this.parent = parent;
	}

	public String getParent() {
		return parent;
	}

}