/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class MEMBERElement {
	@SerializedName("ACCOUNT_NO")
	private String account_no;

 	public void setAccount_no(String account_no) {
		this.account_no = account_no;
	}

	public String getAccount_no() {
		return account_no;
	}

	@SerializedName("NAMEINFO")
	private NAMEINFO nameinfo;

 	public void setNameinfo(NAMEINFO nameinfo) {
		this.nameinfo = nameinfo;
	}

	public NAMEINFO getNameinfo() {
		return nameinfo;
	}

	@SerializedName("POID")
	private String poid;

 	public void setPoid(String poid) {
		this.poid = poid;
	}

	public String getPoid() {
		return poid;
	}

	@SerializedName("CONN_TYPE")
	private Integer conn_type;

 	public void setConn_type(Integer conn_type) {
		this.conn_type = conn_type;
	}

	public Integer getConn_type() {
		return conn_type;
	}

	@SerializedName("GROUP_OBJ")
	private String group_obj;

 	public void setGroup_obj(String group_obj) {
		this.group_obj = group_obj;
	}

	public String getGroup_obj() {
		return group_obj;
	}

	@SerializedName("elem")
	private Integer elem;

 	public void setElem(Integer elem) {
		this.elem = elem;
	}

	public Integer getElem() {
		return elem;
	}

}