/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class MSO_FLD_ORG_STRUCTURE {
	
	@SerializedName("ACCOUNT_NO")
	private String account_no;

 	public void setAccount_no(String account_no) {
		this.account_no = account_no;
	}

	public String getAccount_no() {
		return account_no;
	}

	@SerializedName("NAMEINFO")
	private NAMEINFO nameinfo;

 	public void setNameinfo(NAMEINFO nameinfo) {
		this.nameinfo = nameinfo;
	}

	public NAMEINFO getNameinfo() {
		return nameinfo;
	}

	@SerializedName("MSO_FLD_PP_TYPE")
	private Integer mso_fld_pp_type;

 	public void setMso_fld_pp_type(Integer mso_fld_pp_type) {
		this.mso_fld_pp_type = mso_fld_pp_type;
	}

	public Integer getMso_fld_pp_type() {
		return mso_fld_pp_type;
	}

	@SerializedName("MSO_FLD_PAN_NO")
	private String mso_fld_pan_no;

 	public void setMso_fld_pan_no(String mso_fld_pan_no) {
		this.mso_fld_pan_no = mso_fld_pan_no;
	}

	public String getMso_fld_pan_no() {
		return mso_fld_pan_no;
	}

	@SerializedName("PROFILE_OBJ")
	private String profile_obj;

 	public void setProfile_obj(String profile_obj) {
		this.profile_obj = profile_obj;
	}

	public String getProfile_obj() {
		return profile_obj;
	}

	@SerializedName("MSO_FLD_SALES_CLOSE_TYPE")
	private Integer mso_fld_sales_close_type;

 	public void setMso_fld_sales_close_type(Integer mso_fld_sales_close_type) {
		this.mso_fld_sales_close_type = mso_fld_sales_close_type;
	}

	public Integer getMso_fld_sales_close_type() {
		return mso_fld_sales_close_type;
	}

	@SerializedName("MSO_FLD_LCO_OBJ")
	private String mso_fld_lco_obj;

 	public void setMso_fld_lco_obj(String mso_fld_lco_obj) {
		this.mso_fld_lco_obj = mso_fld_lco_obj;
	}

	public String getMso_fld_lco_obj() {
		return mso_fld_lco_obj;
	}

	@SerializedName("CUSTOMER_TYPE")
	private Integer customer_type;

 	public void setCustomer_type(Integer customer_type) {
		this.customer_type = customer_type;
	}

	public Integer getCustomer_type() {
		return customer_type;
	}

	@SerializedName("PARENT")
	private String parent;

 	public void setParent(String parent) {
		this.parent = parent;
	}

	public String getParent() {
		return parent;
	}

	@SerializedName("MSO_FLD_WELCOME_CALL_STATUS")
	private Integer mso_fld_welcome_call_status;

 	public void setMso_fld_welcome_call_status(Integer mso_fld_welcome_call_status) {
		this.mso_fld_welcome_call_status = mso_fld_welcome_call_status;
	}

	public Integer getMso_fld_welcome_call_status() {
		return mso_fld_welcome_call_status;
	}

	@SerializedName("MSO_FLD_SDT_OBJ")
	private String mso_fld_sdt_obj;

 	public void setMso_fld_sdt_obj(String mso_fld_sdt_obj) {
		this.mso_fld_sdt_obj = mso_fld_sdt_obj;
	}

	public String getMso_fld_sdt_obj() {
		return mso_fld_sdt_obj;
	}

	@SerializedName("MSO_FLD_CATV_ACCOUNT_OBJ")
	private String mso_fld_catv_account_obj;

 	public void setMso_fld_catv_account_obj(String mso_fld_catv_account_obj) {
		this.mso_fld_catv_account_obj = mso_fld_catv_account_obj;
	}

	public String getMso_fld_catv_account_obj() {
		return mso_fld_catv_account_obj;
	}

	@SerializedName("MSO_FLD_SALESMAN_OBJ")
	private String mso_fld_salesman_obj;

 	public void setMso_fld_salesman_obj(String mso_fld_salesman_obj) {
		this.mso_fld_salesman_obj = mso_fld_salesman_obj;
	}

	public String getMso_fld_salesman_obj() {
		return mso_fld_salesman_obj;
	}

	@SerializedName("MSO_FLD_JV_OBJ")
	private String mso_fld_jv_obj;

 	public void setMso_fld_jv_obj(String mso_fld_jv_obj) {
		this.mso_fld_jv_obj = mso_fld_jv_obj;
	}

	public String getMso_fld_jv_obj() {
		return mso_fld_jv_obj;
	}

	@SerializedName("MSO_FLD_DT_OBJ")
	private String mso_fld_dt_obj;

 	public void setMso_fld_dt_obj(String mso_fld_dt_obj) {
		this.mso_fld_dt_obj = mso_fld_dt_obj;
	}

	public String getMso_fld_dt_obj() {
		return mso_fld_dt_obj;
	}

	@SerializedName("MSO_FLD_DAS_TYPE")
	private String mso_fld_das_type;

 	public void setMso_fld_das_type(String mso_fld_das_type) {
		this.mso_fld_das_type = mso_fld_das_type;
	}

	public String getMso_fld_das_type() {
		return mso_fld_das_type;
	}

}