/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class MSO_FLD_CATV_INFO {
	@SerializedName("MSO_FLD_CARF_RECEIVED")
	private Integer mso_fld_carf_received;

 	public void setMso_fld_carf_received(Integer mso_fld_carf_received) {
		this.mso_fld_carf_received = mso_fld_carf_received;
	}

	public Integer getMso_fld_carf_received() {
		return mso_fld_carf_received;
	}

	@SerializedName("MSO_FLD_CAS_SUBSCRIBER_ID")
	private String mso_fld_cas_subscriber_id;

 	public void setMso_fld_cas_subscriber_id(String mso_fld_cas_subscriber_id) {
		this.mso_fld_cas_subscriber_id = mso_fld_cas_subscriber_id;
	}

	public String getMso_fld_cas_subscriber_id() {
		return mso_fld_cas_subscriber_id;
	}

	@SerializedName("MSO_FLD_REGION_KEY")
	private String mso_fld_region_key;

 	public void setMso_fld_region_key(String mso_fld_region_key) {
		this.mso_fld_region_key = mso_fld_region_key;
	}

	public String getMso_fld_region_key() {
		return mso_fld_region_key;
	}

	@SerializedName("CONN_TYPE")
	private Integer conn_type;

 	public void setConn_type(Integer conn_type) {
		this.conn_type = conn_type;
	}

	public Integer getConn_type() {
		return conn_type;
	}

	@SerializedName("MSO_FLD_BOUQUET_ID")
	private String mso_fld_bouquet_id;

 	public void setMso_fld_bouquet_id(String mso_fld_bouquet_id) {
		this.mso_fld_bouquet_id = mso_fld_bouquet_id;
	}

	public String getMso_fld_bouquet_id() {
		return mso_fld_bouquet_id;
	}

	@SerializedName("MSO_FLD_CARF_ID")
	private String mso_fld_carf_id;

 	public void setMso_fld_carf_id(String mso_fld_carf_id) {
		this.mso_fld_carf_id = mso_fld_carf_id;
	}

	public String getMso_fld_carf_id() {
		return mso_fld_carf_id;
	}

	@SerializedName("MSO_FLD_ADDRESS_VERIFIED")
	private Integer mso_fld_address_verified;

 	public void setMso_fld_address_verified(Integer mso_fld_address_verified) {
		this.mso_fld_address_verified = mso_fld_address_verified;
	}

	public Integer getMso_fld_address_verified() {
		return mso_fld_address_verified;
	}

	@SerializedName("MSO_FLD_NETWORK_NODE")
	private String mso_fld_network_node;

 	public void setMso_fld_network_node(String mso_fld_network_node) {
		this.mso_fld_network_node = mso_fld_network_node;
	}

	public String getMso_fld_network_node() {
		return mso_fld_network_node;
	}

	@SerializedName("DELIVERY_STATUS")
	private Integer delivery_status;

 	public void setDelivery_status(Integer delivery_status) {
		this.delivery_status = delivery_status;
	}

	public Integer getDelivery_status() {
		return delivery_status;
	}

	@SerializedName("MSO_FLD_SALESMAN_OBJ")
	private String mso_fld_salesman_obj;

 	public void setMso_fld_salesman_obj(String mso_fld_salesman_obj) {
		this.mso_fld_salesman_obj = mso_fld_salesman_obj;
	}

	public String getMso_fld_salesman_obj() {
		return mso_fld_salesman_obj;
	}

	@SerializedName("MSO_FLD_LEGACY_AGR_NO")
	private String mso_fld_legacy_agr_no;

 	public void setMso_fld_legacy_agr_no(String mso_fld_legacy_agr_no) {
		this.mso_fld_legacy_agr_no = mso_fld_legacy_agr_no;
	}

	public String getMso_fld_legacy_agr_no() {
		return mso_fld_legacy_agr_no;
	}

	@SerializedName("MSO_FLD_BOX_INSTALLED_T")
	private String mso_fld_box_installed_t;

 	public void setMso_fld_box_installed_t(String mso_fld_box_installed_t) {
		this.mso_fld_box_installed_t = mso_fld_box_installed_t;
	}

	public String getMso_fld_box_installed_t() {
		return mso_fld_box_installed_t;
	}

	@SerializedName("MSO_FLD_CAF_UPDATE_COUNT")
	private Integer mso_fld_caf_update_count;

 	public void setMso_fld_caf_update_count(Integer mso_fld_caf_update_count) {
		this.mso_fld_caf_update_count = mso_fld_caf_update_count;
	}

	public Integer getMso_fld_caf_update_count() {
		return mso_fld_caf_update_count;
	}

	@SerializedName("MSO_FLD_LCO_BOX_RECV_T")
	private String mso_fld_lco_box_recv_t;

 	public void setMso_fld_lco_box_recv_t(String mso_fld_lco_box_recv_t) {
		this.mso_fld_lco_box_recv_t = mso_fld_lco_box_recv_t;
	}

	public String getMso_fld_lco_box_recv_t() {
		return mso_fld_lco_box_recv_t;
	}

	@SerializedName("MSO_FLD_AGREEMENT_NO")
	private String mso_fld_agreement_no;

 	public void setMso_fld_agreement_no(String mso_fld_agreement_no) {
		this.mso_fld_agreement_no = mso_fld_agreement_no;
	}

	public String getMso_fld_agreement_no() {
		return mso_fld_agreement_no;
	}

}