/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class NAMEINFOElement {
	@SerializedName("SERVICE_OBJ")
	private String service_obj;

 	public void setService_obj(String service_obj) {
		this.service_obj = service_obj;
	}

	public String getService_obj() {
		return service_obj;
	}

	@SerializedName("MIDDLE_NAME")
	private String middle_name;

 	public void setMiddle_name(String middle_name) {
		this.middle_name = middle_name;
	}

	public String getMiddle_name() {
		return middle_name;
	}

	@SerializedName("MSO_FLD_DISTRICT_NAME")
	private String mso_fld_district_name;

 	public void setMso_fld_district_name(String mso_fld_district_name) {
		this.mso_fld_district_name = mso_fld_district_name;
	}

	public String getMso_fld_district_name() {
		return mso_fld_district_name;
	}

	@SerializedName("MSO_FLD_LANDMARK")
	private String mso_fld_landmark;

 	public void setMso_fld_landmark(String mso_fld_landmark) {
		this.mso_fld_landmark = mso_fld_landmark;
	}

	public String getMso_fld_landmark() {
		return mso_fld_landmark;
	}

	@SerializedName("ZIP")
	private Integer zip;

 	public void setZip(Integer zip) {
		this.zip = zip;
	}

	public Integer getZip() {
		return zip;
	}

	@SerializedName("SALUTATION")
	private String salutation;

 	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	public String getSalutation() {
		return salutation;
	}

	@SerializedName("CONTACT_TYPE")
	private String contact_type;

 	public void setContact_type(String contact_type) {
		this.contact_type = contact_type;
	}

	public String getContact_type() {
		return contact_type;
	}

	@SerializedName("COUNTRY")
	private String country;

 	public void setCountry(String country) {
		this.country = country;
	}

	public String getCountry() {
		return country;
	}

	@SerializedName("STATE")
	private String state;

 	public void setState(String state) {
		this.state = state;
	}

	public String getState() {
		return state;
	}

	@SerializedName("GEOCODE")
	private String geocode;

 	public void setGeocode(String geocode) {
		this.geocode = geocode;
	}

	public String getGeocode() {
		return geocode;
	}

	@SerializedName("MSO_FLD_LOCATION_NAME")
	private String mso_fld_location_name;

 	public void setMso_fld_location_name(String mso_fld_location_name) {
		this.mso_fld_location_name = mso_fld_location_name;
	}

	public String getMso_fld_location_name() {
		return mso_fld_location_name;
	}

	@SerializedName("FIRST_NAME")
	private String first_name;

 	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}

	public String getFirst_name() {
		return first_name;
	}

	@SerializedName("CANON_COUNTRY")
	private String canon_country;

 	public void setCanon_country(String canon_country) {
		this.canon_country = canon_country;
	}

	public String getCanon_country() {
		return canon_country;
	}

	@SerializedName("LAST_NAME")
	private String last_name;

 	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}

	public String getLast_name() {
		return last_name;
	}

	@SerializedName("MIDDLE_CANON")
	private String middle_canon;

 	public void setMiddle_canon(String middle_canon) {
		this.middle_canon = middle_canon;
	}

	public String getMiddle_canon() {
		return middle_canon;
	}

	@SerializedName("LAST_CANON")
	private String last_canon;

 	public void setLast_canon(String last_canon) {
		this.last_canon = last_canon;
	}

	public String getLast_canon() {
		return last_canon;
	}

	@SerializedName("TITLE")
	private String title;

 	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle() {
		return title;
	}

	@SerializedName("MSO_FLD_STREET_NAME")
	private String mso_fld_street_name;

 	public void setMso_fld_street_name(String mso_fld_street_name) {
		this.mso_fld_street_name = mso_fld_street_name;
	}

	public String getMso_fld_street_name() {
		return mso_fld_street_name;
	}

	@SerializedName("MSO_FLD_BUILDING_NAME")
	private String mso_fld_building_name;

 	public void setMso_fld_building_name(String mso_fld_building_name) {
		this.mso_fld_building_name = mso_fld_building_name;
	}

	public String getMso_fld_building_name() {
		return mso_fld_building_name;
	}

	@SerializedName("FIRST_CANON")
	private String first_canon;

 	public void setFirst_canon(String first_canon) {
		this.first_canon = first_canon;
	}

	public String getFirst_canon() {
		return first_canon;
	}

	@SerializedName("TAXPKG_TYPE")
	private Integer taxpkg_type;

 	public void setTaxpkg_type(Integer taxpkg_type) {
		this.taxpkg_type = taxpkg_type;
	}

	public Integer getTaxpkg_type() {
		return taxpkg_type;
	}

	@SerializedName("ADDRESS")
	private String address;

 	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress() {
		return address;
	}

	@SerializedName("CANON_COMPANY")
	private String canon_company;

 	public void setCanon_company(String canon_company) {
		this.canon_company = canon_company;
	}

	public String getCanon_company() {
		return canon_company;
	}

	@SerializedName("elem")
	private String elem;

 	/*public void setElem(Integer elem) {
		this.elem = elem;
	}*/

	public Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@SerializedName("MSO_FLD_AREA_NAME")
	private String mso_fld_area_name;

 	public void setMso_fld_area_name(String mso_fld_area_name) {
		this.mso_fld_area_name = mso_fld_area_name;
	}

	public String getMso_fld_area_name() {
		return mso_fld_area_name;
	}

	@SerializedName("CITY")
	private String city;

 	public void setCity(String city) {
		this.city = city;
	}

	public String getCity() {
		return city;
	}

	@SerializedName("EMAIL_ADDR")
	private String email_addr;

 	public void setEmail_addr(String email_addr) {
		this.email_addr = email_addr;
	}

	public String getEmail_addr() {
		return email_addr;
	}

	@SerializedName("COMPANY")
	private String company;

 	public void setCompany(String company) {
		this.company = company;
	}

	public String getCompany() {
		return company;
	}

	@SerializedName("PHONES")
	private PHONElement[] phones;

 	public void setPhones(PHONElement[] phones) {
		this.phones = phones;
	}

	public PHONElement[] getPhones() {
		return phones;
	}

}