/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class NAMEINFO {
	@SerializedName("MIDDLE_NAME")
	private String middle_name;

 	public void setMiddle_name(String middle_name) {
		this.middle_name = middle_name;
	}

	public String getMiddle_name() {
		return middle_name;
	}

	@SerializedName("COMPANY")
	private String company;

 	public void setCompany(String company) {
		this.company = company;
	}

	public String getCompany() {
		return company;
	}

	@SerializedName("FIRST_NAME")
	private String first_name;

 	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}

	public String getFirst_name() {
		return first_name;
	}

	@SerializedName("LAST_NAME")
	private String last_name;

 	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}

	public String getLast_name() {
		return last_name;
	}

	@SerializedName("elem")
	private String elem;

 	/*public void setElem(Integer elem) {
		this.elem = elem;
	}*/

	public Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@SerializedName("ACCOUNT_TYPE")
	private Integer account_type;

 	public void setAccount_type(Integer account_type) {
		this.account_type = account_type;
	}

	public Integer getAccount_type() {
		return account_type;
	}

}