/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class PLAN_LISTElement {
	@SerializedName("PLAN")
	private PLANElement[] plan;

 	public void setPlan(PLANElement[] plan) {
		this.plan = plan;
	}

	public PLANElement[] getPlan() {
		return plan;
	}

	@SerializedName("elem")
	private String elem;

 	/*public void setElem(Integer elem) {
		this.elem = elem;
	}*/

	public Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

}