/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class PLANElement {
	/*@SerializedName("PRODUCTS")
	private PRODUCTS products;

 	public void setProducts(PRODUCTS products) {
		this.products = products;
	}

	public PRODUCTS getProducts() {
		return products;
	}*/

	@SerializedName("PRODUCTS")
	private PRODUCTElement[] products;

	public void setProducts(PRODUCTElement[] products) {
		this.products = products;
	}

	public PRODUCTElement[] getProducts() {
		return products;
	}
	
	@SerializedName("PLAN_OBJ")
	private String plan_obj;

 	public void setPlan_obj(String plan_obj) {
		this.plan_obj = plan_obj;
	}

	public String getPlan_obj() {
		return plan_obj;
	}

	@SerializedName("elem")
	private String elem;

 	/*public void setElem(java.lang.Integer elem) {
		this.elem = elem;
	}*/

	public java.lang.Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

}