/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class PRODUCTElement {
	@SerializedName("PACKAGE_ID")
	private Integer package_id;

 	public void setPackage_id(Integer package_id) {
		this.package_id = package_id;
	}

	public Integer getPackage_id() {
		return package_id;
	}

	@SerializedName("EFFECTIVE_T")
	private String effective_t;

 	public void setEffective_t(String effective_t) {
		this.effective_t = effective_t;
	}

	public String getEffective_t() {
		return effective_t;
	}

	@SerializedName("PRODUCT_OBJ")
	private String product_obj;

 	public void setProduct_obj(String product_obj) {
		this.product_obj = product_obj;
	}

	public String getProduct_obj() {
		return product_obj;
	}

	@SerializedName("USAGE_START_T")
	private String usage_start_t;

 	public void setUsage_start_t(String usage_start_t) {
		this.usage_start_t = usage_start_t;
	}

	public String getUsage_start_t() {
		return usage_start_t;
	}

	@SerializedName("POID")
	private String poid;

 	public void setPoid(String poid) {
		this.poid = poid;
	}

	public String getPoid() {
		return poid;
	}

	@SerializedName("PURCHASE_START_T")
	private String purchase_start_t;

 	public void setPurchase_start_t(String purchase_start_t) {
		this.purchase_start_t = purchase_start_t;
	}

	public String getPurchase_start_t() {
		return purchase_start_t;
	}

	@SerializedName("CYCLE_START_T")
	private String cycle_start_t;

 	public void setCycle_start_t(String cycle_start_t) {
		this.cycle_start_t = cycle_start_t;
	}

	public String getCycle_start_t() {
		return cycle_start_t;
	}

	@SerializedName("DEAL_OBJ")
	private String deal_obj;

 	public void setDeal_obj(String deal_obj) {
		this.deal_obj = deal_obj;
	}

	public String getDeal_obj() {
		return deal_obj;
	}

	@SerializedName("elem")
	private String elem;

 	/*public void setElem(Integer elem) {
		this.elem = elem;
	}*/

	public Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@SerializedName("STATUS")
	private Integer status;

 	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getStatus() {
		return status;
	}

	@SerializedName("PURCHASE_END_T")
	private String purchase_end_t;

 	public void setPurchase_end_t(String purchase_end_t) {
		this.purchase_end_t = purchase_end_t;
	}

	public String getPurchase_end_t() {
		return purchase_end_t;
	}

}