/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class SERVICEElement {
	@SerializedName("MSO_FLD_CATV_INFO")
	private MSO_FLD_CATV_INFO mso_fld_catv_info;

 	public void setMso_fld_catv_info(MSO_FLD_CATV_INFO mso_fld_catv_info) {
		this.mso_fld_catv_info = mso_fld_catv_info;
	}

	public MSO_FLD_CATV_INFO getMso_fld_catv_info() {
		return mso_fld_catv_info;
	}

	@SerializedName("LOGIN")
	private String login;

 	public void setLogin(String login) {
		this.login = login;
	}

	public String getLogin() {
		return login;
	}

	@SerializedName("SERVICE_ID")
	private String service_id;

 	public void setService_id(String service_id) {
		this.service_id = service_id;
	}

	public String getService_id() {
		return service_id;
	}

	@SerializedName("AAC_ACCESS")
	private String aac_access;

 	public void setAac_access(String aac_access) {
		this.aac_access = aac_access;
	}

	public String getAac_access() {
		return aac_access;
	}

	@SerializedName("CREATED_T")
	private String created_t;

 	public void setCreated_t(String created_t) {
		this.created_t = created_t;
	}

	public String getCreated_t() {
		return created_t;
	}

	@SerializedName("PROFILE_OBJ")
	private String profile_obj;

 	public void setProfile_obj(String profile_obj) {
		this.profile_obj = profile_obj;
	}

	public String getProfile_obj() {
		return profile_obj;
	}

	@SerializedName("BAL_GRP_OBJ")
	private String bal_grp_obj;

 	public void setBal_grp_obj(String bal_grp_obj) {
		this.bal_grp_obj = bal_grp_obj;
	}

	public String getBal_grp_obj() {
		return bal_grp_obj;
	}

	@SerializedName("LASTSTAT_CMNT")
	private String laststat_cmnt;

 	public void setLaststat_cmnt(String laststat_cmnt) {
		this.laststat_cmnt = laststat_cmnt;
	}

	public String getLaststat_cmnt() {
		return laststat_cmnt;
	}

	@SerializedName("SERVICE_STATE_EXPIRATION_T")
	private String service_state_expiration_t;

 	public void setService_state_expiration_t(String service_state_expiration_t) {
		this.service_state_expiration_t = service_state_expiration_t;
	}

	public String getService_state_expiration_t() {
		return service_state_expiration_t;
	}

	@SerializedName("MOD_T")
	private String mod_t;

 	public void setMod_t(String mod_t) {
		this.mod_t = mod_t;
	}

	public String getMod_t() {
		return mod_t;
	}

	@SerializedName("TYPE")
	private Integer type;

 	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getType() {
		return type;
	}

	@SerializedName("READ_ACCESS")
	private String read_access;

 	public void setRead_access(String read_access) {
		this.read_access = read_access;
	}

	public String getRead_access() {
		return read_access;
	}

	@SerializedName("LIFECYCLE_STATE")
	private Integer lifecycle_state;

 	public void setLifecycle_state(Integer lifecycle_state) {
		this.lifecycle_state = lifecycle_state;
	}

	public Integer getLifecycle_state() {
		return lifecycle_state;
	}

	@SerializedName("PASSWD_EXPIRATION_T")
	private String passwd_expiration_t;

 	public void setPasswd_expiration_t(String passwd_expiration_t) {
		this.passwd_expiration_t = passwd_expiration_t;
	}

	public String getPasswd_expiration_t() {
		return passwd_expiration_t;
	}

	@SerializedName("STATUS_FLAGS")
	private Integer status_flags;

 	public void setStatus_flags(Integer status_flags) {
		this.status_flags = status_flags;
	}

	public Integer getStatus_flags() {
		return status_flags;
	}

	@SerializedName("NEXT_ITEM_POID_LIST")
	private String next_item_poid_list;

 	public void setNext_item_poid_list(String next_item_poid_list) {
		this.next_item_poid_list = next_item_poid_list;
	}

	public String getNext_item_poid_list() {
		return next_item_poid_list;
	}

	@SerializedName("PASSWD_STATUS")
	private Integer passwd_status;

 	public void setPasswd_status(Integer passwd_status) {
		this.passwd_status = passwd_status;
	}

	public Integer getPasswd_status() {
		return passwd_status;
	}

	@SerializedName("PLAN_LISTS")
	private PLAN_LISTElement[] plan_lists;

 	public void setPlan_lists(PLAN_LISTElement[] plan_lists) {
		this.plan_lists = plan_lists;
	}

	public PLAN_LISTElement[] getPlan_lists() {
		return plan_lists;
	}

	@SerializedName("WRITE_ACCESS")
	private String write_access;

 	public void setWrite_access(String write_access) {
		this.write_access = write_access;
	}

	public String getWrite_access() {
		return write_access;
	}

	@SerializedName("SUBSCRIPTION_OBJ")
	private String subscription_obj;

 	public void setSubscription_obj(String subscription_obj) {
		this.subscription_obj = subscription_obj;
	}

	public String getSubscription_obj() {
		return subscription_obj;
	}

	@SerializedName("STATUS")
	private String status;

 	/*public void setStatus(Integer status) {
		this.status = status;
	}*/

	public Integer getStatus() {
		if(status == null || status.equals(""))
			return 0;
		else
		return Integer.valueOf(status);
	}

	@SerializedName("EFFECTIVE_T")
	private String effective_t;

 	public void setEffective_t(String effective_t) {
		this.effective_t = effective_t;
	}

	public String getEffective_t() {
		return effective_t;
	}

	@SerializedName("POID")
	private String poid;

 	public void setPoid(String poid) {
		this.poid = poid;
	}

	public String getPoid() {
		return poid;
	}

	@SerializedName("CLOSE_WHEN_T")
	private String close_when_t;

 	public void setClose_when_t(String close_when_t) {
		this.close_when_t = close_when_t;
	}

	public String getClose_when_t() {
		return close_when_t;
	}

	@SerializedName("AAC_VENDOR")
	private String aac_vendor;

 	public void setAac_vendor(String aac_vendor) {
		this.aac_vendor = aac_vendor;
	}

	public String getAac_vendor() {
		return aac_vendor;
	}

	@SerializedName("AAC_SOURCE")
	private String aac_source;

 	public void setAac_source(String aac_source) {
		this.aac_source = aac_source;
	}

	public String getAac_source() {
		return aac_source;
	}

	@SerializedName("OBJECT_CACHE_TYPE")
	private Integer object_cache_type;

 	public void setObject_cache_type(Integer object_cache_type) {
		this.object_cache_type = object_cache_type;
	}

	public Integer getObject_cache_type() {
		return object_cache_type;
	}

	@SerializedName("AAC_SERIAL_NUM")
	private String aac_serial_num;

 	public void setAac_serial_num(String aac_serial_num) {
		this.aac_serial_num = aac_serial_num;
	}

	public String getAac_serial_num() {
		return aac_serial_num;
	}

	@SerializedName("elem")
	private String elem;

 	/*public void setElem(Integer elem) {
		this.elem = elem;
	}*/

	public Integer getElem() {
		if(elem == null || elem.equals(""))
			return 0;
		else
		return Integer.valueOf(elem);
	}

	@SerializedName("ALIAS_LIST")
	private ALIAS_LISTElement[] alias_list;

 	public void setAlias_list(ALIAS_LISTElement[] alias_list) {
		this.alias_list = alias_list;
	}

	public ALIAS_LISTElement[] getAlias_list() {
		return alias_list;
	}

	@SerializedName("LAST_STATUS_T")
	private String last_status_t;

 	public void setLast_status_t(String last_status_t) {
		this.last_status_t = last_status_t;
	}

	public String getLast_status_t() {
		return last_status_t;
	}

	@SerializedName("AAC_PACKAGE")
	private String aac_package;

 	public void setAac_package(String aac_package) {
		this.aac_package = aac_package;
	}

	public String getAac_package() {
		return aac_package;
	}

	@SerializedName("AAC_PROMO_CODE")
	private String aac_promo_code;

 	public void setAac_promo_code(String aac_promo_code) {
		this.aac_promo_code = aac_promo_code;
	}

	public String getAac_promo_code() {
		return aac_promo_code;
	}

	@SerializedName("NAME")
	private String name;

 	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	@SerializedName("ACCOUNT_OBJ")
	private String account_obj;

 	public void setAccount_obj(String account_obj) {
		this.account_obj = account_obj;
	}

	public String getAccount_obj() {
		return account_obj;
	}

	@SerializedName("DEVICES")
	private DEVICEElement[] devices;

 	public void setDevices(DEVICEElement[] devices) {
		this.devices = devices;
	}

	public DEVICEElement[] getDevices() {
		return devices;
	}

	@SerializedName("ITEM_POID_LIST")
	private String item_poid_list;

 	public void setItem_poid_list(String item_poid_list) {
		this.item_poid_list = item_poid_list;
	}

	public String getItem_poid_list() {
		return item_poid_list;
	}

	@SerializedName("PASSWD")
	private String passwd;

 	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public String getPasswd() {
		return passwd;
	}

}