/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.org.brm.data;

import com.google.gson.annotations.SerializedName;

public class SERVICE_INFO {
	
	@SerializedName("SERVICES")
	private SERVICEElement[] services;

 	public void setServices(SERVICEElement[] services) {
		this.services = services;
	}

	public SERVICEElement[] getServices() {
		return services;
	}

}